SOLVER:
  BATCH_SIZE: 128
  MAX_EPOCH: 10
  LR: 5e-5
  SEED: 42
  NUM_WORKERS: 12

DECODER:
  MULTI_TASK: True
  IN_DIM: 256
  HIDDEN_DIM: 256

COMET:
  PROJECT_NAME: "GPCR-Quadnet"
  TAG: "MultiTask_NonDA"

PROTEIN:
  ESM_MODEL: "esm2_t33_650M_UR50D"
  EMBED_DIM: 1280

RESULT:
  OUTPUT_DIR: "./results/"
